### ISSUE TITLE
Move to YunoHost-Apps?

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/kodi_ynh#1]
Hello
The package seems great, and I'll see if I can give a hand.
Can you transfer the repository to YunoHost-Apps to ease collaboration?
Thanks in advance

**Comment by sy6sy2** [comment]
Hello scith,
Thank you for your message!
Yes of course, I can do that!

**Comment by sy6sy2** [comment]
Are you able to do the necessary stuff to add my GitHub account to YunoHost-Apps organization in order to transfer this repo?

**Comment by scith** [comment]
hHi, done thanks

**Comment by sy6sy2** [comment]
Thanks, I will transfer the repo soon!

**Comment by sy6sy2** [comment]
Transfer done :D
