### ISSUE TITLE
Kodi on buster and YunoHost 4

### ISSUE THREAD

**Issue by Gredin67** [YunoHost-Apps/kodi_ynh#6]
Hi I would try to install kodi on my x86/64 yunohost 4. I'll try to get it work if it fails. It is also missing a testing branch. Could you give me access to the repo?

**Comment by sy6sy2** [comment]
Hi,
It seems that I do not have the ability to access this repo settings. @yalh76 can you do it please?

**Comment by yalh76** [comment]
testing branch created ;)

**Comment by yalh76** [comment]
And maintain rights granted to this repo ;p

**Comment by sy6sy2** [comment]
Thank you 😉

**Comment by Gredin67** [comment]
Can you give me a short update on your last status? What was working and what was not? Does it make send to merge the pending PR?

Was the plan to have kodi running on the server with external screen (self-hosting use-case) or just to run it headless and with the web interface?

Le 3 juillet 2020 16:46:55 GMT+02:00, Sylvain CECCHETTO <notifications@github.com> a écrit :
>Thank you 😉 >
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/YunoHost-Apps/kodi_ynh/issues/6#issuecomment-653581129

-- Envoyé de /e/ Mail.

**Comment by sy6sy2** [comment]
Sincerely it's been a while...
I guess it's better to start from scratch :-/
I don't use Kodi on YNH since a long time. But before that everything worked like a charm.

The plan was to use Kodi with an external screen.

**Comment by lapineige** [comment]
Now that we are in Debian buster, would it be possible to upgrade the package ? I suppose the installation will be easier… but I don't know the details.
What's needed to do it ? How can I help testing it ?

**Comment by Gredin67** [comment]
You could check what is the status of the kodi package dependencies in debian 10 https://packages.debian.org/fr/buster/kodi
The dependencies of the yunohost package should be updated if necessary. Currently : xserver-xorg-legacy xorg dbus-x11 kodi

Then just try to install the kodi package on a test server. If it fails check the log to see what did not work. If it succeeds try to run kodi using the official instructions. And if you encounter issues to run it, then try to find a solution to solve it or ask for ideas in the yunohost_apps chat

**Comment by Krakinou** [comment]
Hello, Any update on the status?

**Comment by Gredin67** [comment]
Would be very nice if someone could test the package on the testing branch. It could work. I think the remaining issues that I had were coming from my hardware. If it doesn't work, one thing I would try is to first install a Debian with GUI, test if display and graphics acceleration works properly. Then install yunohost and then kodi.

Anyway it is important to debug issues related to hardware and issues related to latest yunohost/Debian changes.

Le 3 avril 2021 15:31:38 GMT+02:00, Krakinou ***@***.***> a écrit :
>Hello? Any update on the status?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/YunoHost-Apps/kodi_ynh/issues/6#issuecomment-812865996

-- Envoyé depuis /e/ Mail.
-- Envoyé depuis /e/ Mail.

**Comment by yalh76** [comment]
Last test on Revision: d16634d676ac55ccb77a9ad7b0f99f9a62399bbd 

![image](https://user-images.githubusercontent.com/30271971/113592154-12eeb900-9635-11eb-9efb-50cbdfc2f298.png)


![image](https://user-images.githubusercontent.com/30271971/113592217-2863e300-9635-11eb-8533-932d7fbfc24b.png)

**Comment by Gredin67** [comment]
I don't think we can test the app with package check or a headless VM. Kodi is too much hardware dependent, we want to test it on a machine connected to a screen, etc.. 

As far as I understand your log, it is failing because the system does not have an input (keyboard, mouse, etc). 

On my laptop some month ago the install was working but there were some issues with the graphics acceleration. One thing that I want to test on my laptop is to first install a Debian distro with GUI, check that graphics acceleration is working and then install yunohost and kodi on top of it.

Le 5 avril 2021 17:34:39 GMT+02:00, yalh76 ***@***.***> a écrit :
>Last test on Revision: d16634d676ac55ccb77a9ad7b0f99f9a62399bbd 
>
>![image](https://user-images.githubusercontent.com/30271971/113592154-12eeb900-9635-11eb-9efb-50cbdfc2f298.png)
>
>
>![image](https://user-images.githubusercontent.com/30271971/113592217-2863e300-9635-11eb-8533-932d7fbfc24b.png)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/YunoHost-Apps/kodi_ynh/issues/6#issuecomment-813457446

-- Envoyé depuis /e/ Mail.

**Comment by siwinter** [comment]
I used your app on a raspberry pi 4. At first glance, the installation runs without any problems. Audio and video are okay.
Can I somehow help, through further tests e.g.

**Comment by Gredin67** [comment]
> I used your app on a raspberry pi 4. At first glance, the installation runs without any problems. Audio and video are okay.

Awesome, I was pretty sure it was just a hardware issue. 

> Can I somehow help, through further tests e.g.

Can you tell us how did you install Yunohost and Raspbian on your Pi4 ? It would help us reproduce a working setup and find out what is not working. Did you install a distro with graphical interface from the beginning? Or were you using it as a pure server (only command line interface), e.g. you used the Yunohost image (https://yunohost.org/en/install/hardware:rpi2plus) before installing Kodi_ynh?

Which branch did you use? Could you test the "example" branch. If it works I would merge it in Master.
Does the web interface "chorus" also work when you click on Kodi in the Yunohost user interface ?

You can help by just continue using kodi_ynh and telling us if there are issues ;)

**Comment by siwinter** [comment]
> Can you tell us how did you install Yunohost and Raspbian on your Pi4 ?

I installed Yunohost manually on the latest Raspberry Pi OS Lite (released 2021-05-07). This is a server version with no desktop environment.

> Which branch did you use? Could you test the "example" branch.

The installation of the testing-branch results in a working system.
Video ok
chorus-webinterface ok
Audio ok
CEC ok 

Result of example-branch:
Video ok
chorus webinterface ok
no Audio
no CEC

Let me know, if you need more infos.

**Comment by Gredin67** [comment]
Can you send the log of kodi's starting in the example branch ?

@yalh76 we have a beta tester here. Maybe you want to understand what makes audio and CEC fail in your example branch. Would be nice to merge it in master sometime, because you did quite a great refactoring to recent packaging standards!

**Comment by siwinter** [comment]
What exactly do you need and how can I forward it to you?
[This](https://paste.yunohost.org/nicajoricel) is, what younohost's admin dashboard offers to share for service kodi just after installing the example branch

**Comment by siwinter** [comment]
Sorry link was wrong should be this one https://paste.yunohost.org/nicajorice

**Comment by siwinter** [comment]
This may be helpful:
You will find complete kodi.log of the  "example" branch here: https://paste.yunohost.org/ajonuduxov.coffeescript
and can compare it with kodi.log of the "testing" branch: https://paste.yunohost.org/relutuveka.sql

**Comment by Gredin67** [comment]
It looks like this was resolved by #9
